### ISSUE TITLE
First placement

### ISSUE THREAD

**Issue by Forestierr** [Montandon-Varoda/BeerSpeed#4]
Juste regarder le placement et le modifier si nécessaire.

## To verify

1.  Placement de composant traversant sous l'écran LCD  ???

2. Grandeur max ?

> Link : [C_KiCad/beer-speed](https://github.com/Montandon-Varoda/BeerSpeed/tree/main/4_Fabrication/Version_00/C_KiCad/beer-speed)

**Comment by Montandon-Varoda** [comment]
ok
